# Generated by Django 3.2.9 on 2021-12-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='pictures')),
                ('loaction', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('test1', 'test1'), ('test2', 'test3')], default='1', max_length=100)),
                ('whatsapp_number', models.CharField(max_length=10)),
            ],
        ),
    ]
