# Generated by Django 3.2.9 on 2021-12-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_customer_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
