# Generated by Django 3.2.9 on 2021-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_rename_photo_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=250)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=250)),
                ('it_or_non_it', models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT')], max_length=10)),
                ('requirements', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=250)),
                ('stage1', models.CharField(max_length=250)),
                ('stage2', models.CharField(max_length=250)),
            ],
        ),
    ]
