# Generated by Django 3.2.9 on 2021-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='it_or_non_it',
        ),
        migrations.AddField(
            model_name='leads',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT')], default='1', max_length=10),
        ),
    ]
