# Generated by Django 3.2.9 on 2021-12-04 07:45

from django.db import migrations, models
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_auto_20211203_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=django.forms.fields.DateTimeField),
        ),
    ]
