# Generated by Django 3.2.9 on 2021-12-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_alter_leads_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_status',
            field=models.CharField(choices=[('junk_leads', 'junk_leads'), ('open_leads', 'open_leads'), ('close_leads', 'close_leads')], max_length=25),
        ),
    ]
