# Generated by Django 3.2.9 on 2021-12-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_alter_leads_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('Person', 'Person'), ('Contractor', 'Contractor'), ('Company', 'Company')], default='1', max_length=100),
        ),
    ]
