# Generated by Django 3.2.9 on 2021-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_auto_20211206_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('company_address', models.CharField(max_length=250)),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_address', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('item_name', models.CharField(max_length=250)),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('gst', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=250)),
                ('terms_and_conditions', models.CharField(max_length=250)),
            ],
        ),
    ]
