# Generated by Django 3.2.9 on 2021-12-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_quotation_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_invoice',
            name='company_name',
            field=models.CharField(choices=[('Alphabetz Solutionz', 'Alphabetz Solutionz'), ('Alphabetz Technologiez', 'Alphabetz Technologiez')], max_length=250),
        ),
    ]
