# Generated by Django 3.2.9 on 2021-12-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_alter_quotation_invoice_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_invoice',
            name='company_name',
            field=models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT')], max_length=250),
        ),
    ]
