# Generated by Django 3.2.9 on 2021-12-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_auto_20211208_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation_invoice',
            old_name='qty',
            new_name='quantity',
        ),
    ]
