# Generated by Django 3.2.9 on 2021-12-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_rename_qty_quotation_invoice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_invoice',
            name='gst',
            field=models.CharField(choices=[('test1', 'test1'), ('test2', 'test2')], max_length=250),
        ),
    ]
