# Generated by Django 3.2.9 on 2021-12-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_alter_quotation_invoice_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('product_code', models.CharField(max_length=250)),
                ('gst', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='products')),
                ('desc', models.TextField()),
            ],
        ),
    ]
