# Generated by Django 3.2.9 on 2021-12-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
