# Generated by Django 3.2.9 on 2021-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation_invoice',
            name='amount',
        ),
        migrations.AddField(
            model_name='quotation_invoice',
            name='UOM',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation_invoice',
            name='hsn_code',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation_invoice',
            name='item_code',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation_invoice',
            name='warranty',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation_invoice',
            name='gst',
            field=models.CharField(choices=[('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%')], max_length=250),
        ),
    ]
