# Generated by Django 3.2.9 on 2021-12-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0028_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='qty',
        ),
    ]
