# Generated by Django 3.2.9 on 2021-12-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_remove_products_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
