# Generated by Django 3.2.9 on 2021-12-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0032_remove_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='rate',
            new_name='price',
        ),
    ]
