# Generated by Django 3.2.9 on 2021-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0033_rename_rate_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='warranty',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
