# Generated by Django 3.2.9 on 2021-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0034_products_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='item_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='uom',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
