# Generated by Django 3.2.9 on 2021-12-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0037_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
