# Generated by Django 3.2.9 on 2021-12-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0041_alter_products_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gst',
            field=models.IntegerField(choices=[('gst1', '5'), ('gst2', '12'), ('gst3', '18'), ('gst4', '28')]),
        ),
    ]
