# Generated by Django 3.2.9 on 2021-12-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0043_alter_products_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='testuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
