# Generated by Django 3.2.9 on 2021-12-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0044_testuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testuser',
            new_name='Testt',
        ),
    ]
