# Generated by Django 3.2.9 on 2021-12-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0046_auto_20211216_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtusers',
            name='name',
        ),
    ]
