# Generated by Django 3.2.9 on 2021-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0047_remove_testtusers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtusers',
            name='name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
