# Generated by Django 3.2.9 on 2021-12-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0050_crm_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crm_Class',
        ),
    ]
