# Generated by Django 3.2.9 on 2021-12-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0052_blogpost_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='member',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
