# Generated by Django 3.2.9 on 2021-12-28 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0053_auto_20211217_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 35, 17, 157048)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 10, 35, 17, 141423)),
        ),
    ]
