# Generated by Django 3.2.9 on 2021-12-28 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0056_auto_20211228_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 11, 31, 11, 331495)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 11, 31, 11, 331495)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 28, 11, 31, 11, 331495)),
        ),
    ]
