# Generated by Django 3.2.9 on 2021-12-30 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0059_auto_20211230_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 14, 45, 34, 816786)),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
