# Generated by Django 3.2.9 on 2022-01-06 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0066_auto_20220105_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_source',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Website', 'Website'), ('Newspaper', 'Newspaper')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 9, 4, 10, 730516)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 9, 4, 10, 730516)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 6, 9, 4, 10, 730516)),
        ),
    ]
