# Generated by Django 3.2.9 on 2022-01-06 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0069_auto_20220106_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='lead_by',
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 11, 10, 21, 653834)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 11, 10, 21, 653834)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 6, 11, 10, 21, 653834)),
        ),
    ]
