# Generated by Django 3.2.9 on 2022-01-06 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0071_auto_20220106_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='staff_name',
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 13, 4, 59, 598101)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 13, 4, 59, 598101)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 6, 13, 4, 59, 598101)),
        ),
    ]
