# Generated by Django 3.2.9 on 2022-01-20 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0074_auto_20220118_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 9, 54, 38, 388810)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 9, 54, 38, 388810)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 9, 54, 38, 387388)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_status',
            field=models.CharField(choices=[('pending leads', 'pending leads'), ('open leads', 'open leads'), ('close leads', 'close leads')], max_length=25),
        ),
    ]
