# Generated by Django 3.2.9 on 2022-01-27 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0077_auto_20220125_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='end_date',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='start_date',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Started', 'Started'), ('On Hold', 'On Hold'), ('End', 'End')], default='Pending', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 15, 12, 20, 978220)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 12, 20, 978220)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 15, 12, 20, 974879)),
        ),
    ]
