# Generated by Django 3.2.9 on 2022-01-27 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0078_auto_20220127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 15, 13, 44, 732075)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 13, 44, 732075)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 15, 13, 44, 729079)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='end_date',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='start_date',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
