# Generated by Django 3.2.9 on 2022-01-27 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0079_auto_20220127_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 17, 1, 34, 138903)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 17, 1, 34, 138903)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 17, 1, 34, 135905)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
