# Generated by Django 3.2.9 on 2022-01-31 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0080_auto_20220127_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='retur_n',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='tools',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 12, 9, 51, 761412)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 12, 9, 51, 761412)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 12, 9, 51, 761412)),
        ),
    ]
