# Generated by Django 3.2.9 on 2022-02-02 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0082_auto_20220202_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 10, 59, 41, 714725)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 10, 59, 41, 714725)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 10, 59, 41, 711727)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='tools',
            field=models.CharField(blank=True, choices=[('Cable', 'Cable'), ('Driller', 'Driller')], max_length=250, null=True),
        ),
    ]
