# Generated by Django 3.2.9 on 2022-02-02 06:01

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0083_auto_20220202_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 11, 31, 52, 712944)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 11, 31, 52, 712944)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 11, 31, 52, 709947)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='tools',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cable', 'Cable'), ('Driller', 'Driller')], max_length=250, null=True),
        ),
    ]
