# Generated by Django 3.2.9 on 2022-02-02 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0085_auto_20220202_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 11, 59, 52, 551390)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 11, 59, 52, 551390)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 11, 59, 52, 551390)),
        ),
        migrations.RemoveField(
            model_name='leads',
            name='tools',
        ),
        migrations.AddField(
            model_name='leads',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='crm_app.Tools'),
        ),
    ]
