# Generated by Django 3.2.9 on 2022-02-02 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0086_auto_20220202_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 40, 3, 862838)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 16, 40, 3, 862838)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 16, 40, 3, 859840)),
        ),
        migrations.RemoveField(
            model_name='leads',
            name='tools',
        ),
        migrations.AddField(
            model_name='leads',
            name='tools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.tools'),
        ),
    ]
