# Generated by Django 3.2.9 on 2022-02-03 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0089_auto_20220202_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 9, 42, 29, 663597)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 9, 42, 29, 663597)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 9, 42, 29, 661597)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='tools',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
