# Generated by Django 3.2.9 on 2022-02-03 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0094_auto_20220203_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 15, 23, 34, 640341)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 15, 23, 34, 640341)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 15, 23, 34, 637342)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='end_date2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='start_date2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
