# Generated by Django 3.2.9 on 2022-02-04 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0096_auto_20220203_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='retur_n',
            new_name='Return',
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 11, 35, 22, 784510)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 11, 35, 22, 784510)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 11, 35, 22, 782512)),
        ),
    ]
