# Generated by Django 3.2.9 on 2022-02-05 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0100_auto_20220205_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 11, 28, 42, 633572)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 11, 28, 42, 633572)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 5, 11, 28, 42, 631573)),
        ),
    ]
