# Generated by Django 3.2.9 on 2022-03-01 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0109_auto_20220301_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 11, 38, 56, 903131)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 11, 38, 56, 903131)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 11, 38, 56, 898135)),
        ),
        migrations.AlterField(
            model_name='products',
            name='uom',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
