# Generated by Django 3.2.9 on 2022-03-01 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0110_auto_20220301_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='desc',
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 12, 3, 49, 479695)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 1, 12, 3, 49, 479695)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 12, 3, 49, 476697)),
        ),
        migrations.AlterField(
            model_name='products',
            name='hsn',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='warranty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
