# Generated by Django 3.2.9 on 2022-03-03 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0113_auto_20220302_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='user',
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 10, 29, 18, 49018)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 10, 29, 18, 49018)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 3, 10, 29, 18, 46021)),
        ),
    ]
