# Generated by Django 3.2.9 on 2022-03-09 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0125_auto_20220309_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subjects',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 15, 7, 40, 575022)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 15, 7, 40, 575022)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 15, 7, 40, 575022)),
        ),
    ]
