# Generated by Django 3.2.9 on 2022-03-10 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0129_auto_20220310_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 13, 15, 35, 208603)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 13, 15, 35, 208603)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 13, 15, 35, 208603)),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Not Stared', 'Not Started'), ('Deferred', 'Deferred'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Waiting For Approval', 'Waiting For Approval')], max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Highest', 'Highest'), ('Low', 'Low'), ('Lowest', 'Lowest')], max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
