# Generated by Django 3.2.9 on 2022-03-10 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0132_auto_20220310_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 16, 39, 44, 916966)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 16, 39, 44, 916966)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 16, 39, 44, 913969)),
        ),
        migrations.AlterField(
            model_name='task',
            name='subjects',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
