# Generated by Django 3.2.9 on 2022-03-17 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0139_auto_20220317_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 12, 40, 48, 723978)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 12, 40, 48, 723978)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 17, 12, 40, 48, 720980)),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Highest', 'Highest'), ('Low', 'Low'), ('Lowest', 'Lowest')], max_length=50, null=True),
        ),
    ]
