# Generated by Django 3.2.9 on 2022-03-18 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0142_auto_20220318_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='customer',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 11, 24, 38, 611494)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 11, 24, 38, 611494)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 11, 24, 38, 607497)),
        ),
    ]
