# Generated by Django 3.2.9 on 2022-03-25 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0145_auto_20220318_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 16, 2, 42, 811760)),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 16, 2, 42, 811760)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 16, 2, 42, 808762)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='stage1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='stage2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
