# Generated by Django 3.2.9 on 2021-12-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_section', '0003_rename_acompany_address_extendedusermodel_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='gst',
            field=models.IntegerField(),
        ),
    ]
