# Generated by Django 3.2.9 on 2021-12-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_section', '0004_alter_extendedusermodel_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='company_address',
            field=models.TextField(),
        ),
    ]
