# Generated by Django 3.2.9 on 2022-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_section', '0005_alter_extendedusermodel_company_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendedusermodel',
            old_name='company_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='extendedusermodel',
            old_name='age',
            new_name='blood_group',
        ),
        migrations.RemoveField(
            model_name='extendedusermodel',
            name='comapny_name',
        ),
        migrations.RemoveField(
            model_name='extendedusermodel',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='extendedusermodel',
            name='title',
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='employe_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='is_staff2',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='is_superviser',
            field=models.BooleanField(default=False, verbose_name='Is customer'),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='phn_number',
            field=models.CharField(max_length=10),
        ),
    ]
