# Generated by Django 3.2.9 on 2022-03-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_section', '0007_auto_20220305_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='phn_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
