# Generated by Django 3.2.9 on 2022-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_section', '0008_auto_20220307_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='is_staff2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='is_superviser',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
