# Generated by Django 3.2.9 on 2022-03-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_section', '0009_auto_20220307_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user-photo'),
        ),
    ]
