# Generated by Django 3.2.9 on 2022-02-05 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50, unique=True)),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('order_Date', models.DateTimeField(default=datetime.datetime(2022, 2, 5, 15, 2, 32, 660345))),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 3, 7, 15, 2, 32, 660345))),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_management_app.cartlist')),
                ('prodt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_management_app.tools_item')),
            ],
        ),
    ]
