# Generated by Django 3.2.9 on 2022-02-18 04:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_management_app', '0003_auto_20220207_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('order_Date', models.DateTimeField(default=datetime.datetime(2022, 2, 18, 9, 38, 27, 539661))),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 3, 20, 9, 38, 27, 539661))),
            ],
        ),
        migrations.RenameModel(
            old_name='CartList',
            new_name='CartListt',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='itemss',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_management_app.cartlistt'),
        ),
        migrations.AddField(
            model_name='itemss',
            name='prodt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_management_app.tools_item'),
        ),
    ]
