# Generated by Django 3.2.9 on 2022-02-18 04:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_management_app', '0004_auto_20220218_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemss',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='itemss',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemss',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools_management_app.cartlistt'),
        ),
        migrations.AlterField(
            model_name='itemss',
            name='order_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 10, 22, 7, 839075), null=True),
        ),
        migrations.AlterField(
            model_name='itemss',
            name='prodt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools_management_app.tools_item'),
        ),
        migrations.AlterField(
            model_name='itemss',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
