# Generated by Django 3.2.9 on 2022-02-19 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_management_app', '0005_auto_20220218_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemss',
            name='order_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 15, 2, 19, 469391), null=True),
        ),
    ]
